package chap03.section04

//fun main() {
//    networkCall(result->{
//        // 네트워크 호출 성공 시 구현부
//    }, error->{
//        // 네트워크 호출에 실패 시 부현부
//    })
//}
//
//fun networkCall(onSuccess: (ResultType)->Unit, onError: (Throwable)->Unit){
//    try {
//        onSuccess(myResult)
//    }catch (e: Throwable){
//        onError(e)
//    }
//}